baseURL: https://wpx.kainonly.com
title: WEPLANX MANUAL
defaultContentLanguage: en
theme: hugo-book

disablePathToLower: true
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
  highlight:
    style: vs

menu:
  after:
    - name: Github
      url: https://github.com/weplanx
      weight: 99

googleAnalytics: "G-HRP1GV8G14"

disqusShortname: "weplanx-shou-ce"

params:
  BookTheme: light
  BookSearch: true
