baseURL: https://wpx.kainonly.com
title: WEPLANX 手册
defaultContentLanguage: zh
theme: hugo-book

disablePathToLower: true
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
  highlight:
    style: vs

languages:
  zh:
    languageName: Chinese
    contentDir: content.zh
    weight: 1
  en:
    languageName: English
    title: WEPLANX MANUAL
    contentDir: content.en
    weight: 2


menu:
  after:
    - name: Github
      url: https://github.com/weplanx
      weight: 99

googleAnalytics: "G-HRP1GV8G14"

disqusShortname: "weplanx-shou-ce"

params:
  BookTheme: light
  BookSearch: true
